### ISSUE TITLE
 Could not pass event PlayerJoinEvent to Hubbly v2.3.0

### ISSUE THREAD

**Issue by rowdyslav** [CalRL/Hubbly#19]
[20:04:23 INFO]: UUID of player rowdyslav is 7cf52cb3-9ff8-3f53-a52b-c479823be60a
[20:04:24 ERROR]: Could not pass event PlayerJoinEvent to Hubbly v2.3.0
java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
        at Hubbly-2.3.1.jar/me.calrl.hubbly.action.actions.TitleAction.execute(TitleAction.java:35) ~[Hubbly-2.3.1.jar:?]
        at Hubbly-2.3.1.jar/me.calrl.hubbly.action.ActionManager.executeAction(ActionManager.java:69) ~[Hubbly-2.3.1.jar:?]
        at Hubbly-2.3.1.jar/me.calrl.hubbly.listeners.player.PlayerJoinListener.onPlayerJoin(PlayerJoinListener.java:88) ~[Hubbly-2.3.1.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2298-a61db94]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:347) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:173) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]    
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:13) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1574) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1551) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1544) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1503) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1510) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1355) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[20:04:24 INFO]: [+] rowdyslav присоединился
[20:04:24 INFO]: rowdyslav[/127.0.0.1:53643] logged in with entity id 7 at ([world]86.55392274365977, 160.0, -31.135978226652018)
>

**Comment by Space-Banane** [comment]
adding more info than just an error would probably be helpful too

**Comment by XeinTDM** [comment]
'TitleAction.java' file. In the 'execute' method at the start of the try catch.

if (args.length != 5) {
            debugMode.warn("Invalid data format, expected 5 args, got " + args.length);
            return; #Exit the method if the data format is incorrect
        }

**Comment by rowdyslav** [comment]
> adding more info than just an error would probably be helpful too

Appears in every server join

config.yml

debug: false

# ----------------#
# Отключенные миры #
# ----------------#

disabled-worlds:
- world_nether

# ----------#
# Движение #
# ----------#

launchpad:
  enabled: true
  type: SLIME_BLOCK
  power: 2
  power_y: 0.5
  # ТОЛЬКО ЦЕЛЫЕ ЧИСЛА
  cooldown: 2

double_jump:
  enabled: true
  power: 1.5
  power_y: 0.5
  # ТОЛЬКО ЦЕЛЫЕ ЧИСЛА
  cooldown: 2

# -------#
# ПРЕДМЕТЫ #
# -------#
playervisibility:
  enabled: true
  visible:
    item: LIME_DYE
    text: '&rИгроки: &aВидимые'
  hidden:
    item: GRAY_DYE
    text: '&rИгроки: &cСкрытые'

item_on_join:
  enabled: true
  forceinventory: true
  features:
    compass:
      enabled: false
      slot: 5
    playervisibility:
      enabled: true
      slot: 9

close_button:
  slot: 23
  material: BARRIER
  name: '&aЗакрыть'

# ---------------#
# Телепортация #
# ---------------#

antivoid:
  enabled: true

spawn:
  world: world
  x: 0
  y: 200
  z: 0
  # YAW И PITCH ОКРУГЛЯЮТСЯ ДО {-135, -90, -45, 0, 45, 90, 135}, ЕСЛИ ИСПОЛЬЗОВАТЬ /SETSPAWN. МОЖНО РУЧНО ВВЕСТИ ЗНАЧЕНИЯ ЗДЕСЬ
  yaw: 0
  pitch: 0

# -----------------#
# НАСТРОЙКИ ИГРОКА #
# -----------------#

player:
  spawn_on_join: true
  fly:
    enabled: true
  join_message:
    enabled: true
    message: '&7[&a+&7]&r %name% присоединился'
  leave_message:
    enabled: true
    message: '&7[&c-&7]&r %name% вышел'
  bossbar:
    enabled: false
    color: PURPLE
    # АНИМАЦИИ В ТИКАХ
    animation:
      change-interval: 40
      texts:
      - '&6&lДобро пожаловать'
      - <#69b320>&lПривет!

actions_on_join:
- '[TITLE] <#FFDF00>Добро пожаловать!;20;70;20'
- '[SOUND] block.note_block.chime'
- '[FIREWORK] BALL;255;0;255;2'

# ---------------------#
# МЕНЕДЖЕР СОБЫТИЙ МИРА #
# ---------------------#

cancel_events:
  block_place: true
  block_break: true
  damage: true
  weather: true
  item_drop: true
  item_pickup: true
  item_throw: true
  hunger: true
  mob_spawn: true
  block_burn: true
  death_messages: true
  leaf_decay: true

anti_world_download:
  enabled: true
  notify_admin: true

# ------------#
# УПРАВЛЕНИЕ #
# ------------#

lock_chat: false

blocked_words:
  enabled: false
  method: '' # Метод может быть STAR (для ****) или CANCEL, чтобы отменить сообщение
  words:
  - Fuck

# %command% = команда, которая выполняется
blocked_commands:
- pl
- plugins
- op
- stop
- reload

# Вы можете использовать инструмент, как BirdFlop RGB, для создания красивых градиентов!
# https://www.birdflop.com/resources/rgb/
announcements:
  enabled: false
  interval: 30 # В секундах
  messages:
    message1:
    - Test2
    - Это второе объявление
    - До свидания

# ----------#
# СООБЩЕНИЯ #
# ----------#

messages:
  no_console: Только игроки могут использовать эту команду!
  no_permission_command: У вас нет прав для использования этой команды!
  no_permission_use: У вас нет прав на использование этого!
  reload: Плагин Hubbly перезагружен
  fly:
    enable: Режим полета включен.
    disable: Режим полета отключен.
  no_fly_enabled: Полет отключен в конфигурации
  blocked_command: Неизвестная команда. Введите "/help" для помощи
  blocked_message: Пожалуйста, не используйте это слово!


serverselector.yml

selector:
  enabled: false
  material: COMPASS
  name: '&6Выбор сервера'
  gui:
    size: 9
    title: Выбор сервера # Title displayed in the GUI
    items:
      first:
        material: DIAMOND
        name: 'First'
        slot: 1
        lore:
          - "This is line 1"
          - "This is line 2 with %player_name%"
        actions:
          - '[PLAYER] kit'
  fill:
    name: " "
    type: "BLACK_STAINED_GLASS_PANE"
  close_button:
    slot: 23
    name: "&aClose"
    material: BARRIER

**Comment by CalRL** [comment]
The issue comes from this line here:
> - '[TITLE] <#FFDF00>Добро пожаловать!;20;70;20'
You're not providing the title action with a subtitle which is required
You can fix this by changing the action to this:
`- '[TITLE] <#FFDF00>Добро `пожаловать!;;20;70;20'`
Adding the second semicolon ( ; ) after the title makes the subtitle null, leading to it not showing on join.

**Comment by rowdyslav** [comment]
ty <3
